
#include "../../../include/words_lib/lib4_3/i_4.h"
const char *i_4[][3] = {
    {"I", "/aɪ/", "pron. 我n. 碘元素；字母Iabbr. 不及物动词 (intransitive verb)"},
    {"ice", "/aɪs/", "n. 冰；冰淇淋；矜持；（俚）钻石vt. 冰镇；结冰vi. 结冰adj. 冰的n. (Ice)人名；(英)艾斯；(法)伊斯"},
    {"idea", "/aɪˈdiːə/", "n. 想法；主意；概念"},
    {"ideal", "/aɪˈdiːəl/", "adj. 理想的；完美的；想象的；不切实际的n. 理想；典范"},
    {"identical", "/aɪˈdentɪkl/", "adj. 同一的；完全相同的n. 完全相同的事物"},
    {"identify", "/aɪˈdentɪfaɪ/", "vt. 确定；鉴定；识别，辨认出；使参与；把……看成一样vi. 确定；认同；一致"},
    {"idiom", "/ˈɪdiəm/", "n. 成语，习语；土话"},
    {"idle", "/ˈaɪdl/", "adj. 闲置的；懒惰的；停顿的vi. 无所事事；虚度；空转vt. 虚度；使空转"},
    {"if", "/ɪf/", " conj.(表条件)如果,(表假设)要是,是否,即使n.条件,设想"},
    {"ignorant", "/ˈɪɡnərənt/", "adj. 无知的；愚昧的"},
    {"ignore", "/ɪɡˈnɔːr/", "vt. 驳回诉讼；忽视；不理睬"},
    {"ill", "/ɪl/", "adj. 生病的；坏的；邪恶的；不吉利的adv. 不利地；恶劣地；几乎不n. 疾病；不幸n. (Ill)人名；(捷、匈)伊尔"},
    {"illegal", "/ɪˈliːɡl/", "adj. 非法的；违法的；违反规则的n. 非法移民，非法劳工"},
    {"illness", "/ˈɪlnəs/", "n. 病；疾病"},
    {"illustrate", "/ˈɪləstreɪt/", "vt. 阐明，举例说明；图解vi. 举例"},
    {"illustration", "/ˌɪləˈstreɪʃn/", "n. 说明；插图；例证；图解"},
    {"image", "/ˈɪmɪdʒ/", "n. 影像；想象；肖像；偶像vt. 想象；反映；象征；作…的像n. (Image)人名；(法)伊马热"},
    {"imaginary", "/ɪˈmædʒɪneri/", "adj. 虚构的，假想的；想象的；虚数的"},
    {"imagination", "/ɪˌmædʒɪˈneɪʃn/", "n. [心理] 想象力；空想；幻想物"},
    {"imagine", "/ɪˈmædʒɪn/", "vt. 想象；猜想；臆断vi. 想象；猜想；想象起来"},
    {"imitate", "/ˈɪmɪteɪt/", "vt. 模仿，仿效；仿造，仿制"},
    {"immediate", "/ɪˈmiːdiət/", "adj. 立即的；直接的；最接近的"},
    {"immediately", "/ɪˈmiːdiətli/", "adv. 立即，立刻；直接地conj. 一…就"},
    {"immense", "/ɪˈmens/", "adj. 巨大的，广大的；无边无际的；非常好的"},
    {"immigrant", "/ˈɪmɪɡrənt/", "adj. 移民的；迁入的n. 移民，侨民"},
    {"impact", "/ˈɪmpækt/", "n. 影响；效果；碰撞；冲击力vt. 挤入，压紧；撞击；对…产生影响vi. 影响；撞击；冲突；压紧（on，upon，with）"},
    {"impatient", "/ɪmˈpeɪʃnt/", "adj. 焦躁的；不耐心的"},
    {"implication", "/ˌɪmplɪˈkeɪʃn/", "n. 含义；暗示；牵连，卷入；可能的结果，影响"},
    {"imply", "/ɪmˈplaɪ/", "vt. 意味；暗示；隐含"},
    {"import", "/ˈɪmpɔːrt/", "n. 进口，进口货；输入；意思，含义；重要性vt. 输入，进口；含…的意思vi. 输入，进口"},
    {"importance", "/ɪmˈpɔːrtns/", "n. 价值；重要；重大；傲慢"},
    {"important", "/ɪmˈpɔːrtnt/", "adj. 重要的，重大的；有地位的；有权力的"},
    {"impose", "/ɪmˈpoʊz/", "vi. 利用；欺骗；施加影响vt. 强加；征税；以…欺骗"},
    {"impossible", "/ɪmˈpɑːsəbl/", "adj. 不可能的；不可能存在的；难以忍受的；不真实的n. 不可能；不可能的事"},
    {"impress", "/ɪmˈpres/", "vt. 盖印；强征；传送；给予某人深刻印象vi. 给人印象n. 印象，印记；特征，痕迹"},
    {"impression", "/ɪmˈpreʃn/", "n. 印象；效果，影响；压痕，印记；感想；曝光（衡量广告被显示的次数。打开一个带有该广告的网页，则该广告的impression 次数增加一次）"},
    {"impressive", "/ɪmˈpresɪv/", "adj. 感人的；令人钦佩的；给人以深刻印象的"},
    {"imprison", "/ɪmˈprɪzn/", "vt. 监禁；关押；使…下狱"},
    {"improve", "/ɪmˈpruːv/", "vt. 改善，增进；提高……的价值vi. 增加；变得更好"},
    {"improvement", "/ɪmˈpruːvmənt/", "n. 改进，改善；提高"},
    {"in", "/ɪn/", " prep.在...之内(上),在...期间,从事于,符合,穿着;adv.进入,朝里,在家,已到达(来临);adj.在里面的,执政的;n.执政者,入口;India,印度;In,元素铟(indium);Intelligent Network,智能网络"},
    {"inch", "/ɪntʃ/", "n. 英寸；身高；少许vt. 使缓慢地移动vi. 慢慢前进n. (Inch)人名；(英)英奇"},
    {"incident", "/ˈɪnsɪdənt/", "n. 事件，事变；插曲adj. [光] 入射的；附带的；易发生的，伴随而来的"},
    {"incline", "/ɪnˈklaɪn/", "v. 倾向于；（使）倾向于；赞同（某人或某事）；有……倾向；（使）倾斜；低头n. 斜坡；斜面"},
    {"include", "/ɪnˈkluːd/", "vt. 包含，包括"},
    {"income", "/ˈɪnkʌm,ˈɪnkəm/", "n. 收入，收益；所得"},
    {"incorrect", "/ˌɪnkəˈrekt/", "adj. 错误的，不正确的；不适当的；不真实的"},
    {"increase", "/ɪnˈkriːs; ˈɪnkriːs/", "v. 增加；增大；提高；增强n. 增加；增多；增长n. (Increase) （英、美、印、尼日尼亚）英克里斯（人名）"},
    {"increasingly", "/ɪnˈkriːsɪŋli/", "adv. 越来越多地；渐增地"},
    {"indeed", "/ɪnˈdiːd/", "adv. 的确；实在；真正地；甚至int. 真的（表示惊讶、怀疑、讽刺等）"},
    {"indefinite", "/ɪnˈdefɪnət/", "adj. 不确定的；无限的；模糊的"},
    {"independence", "/ˌɪndɪˈpendəns/", "n. 独立性，自立性；自主"},
    {"independent", "/ˌɪndɪˈpendənt/", "adj. 独立的；单独的；无党派的；不受约束的n. 独立自主者；无党派者"},
    {"index", "/ˈɪndeks/", "n. 指标；指数；索引；指针vi. 做索引vt. 指出；编入索引中"},
    {"India", "/ˈɪndiə/", "n. 印度（南亚国家）"},
    {"Indian", "/ˈɪndiən/", "adj.印度的,印度人的,印第安人的n.印度人,印第安人,印第安语"},
    {"indicate", "/ˈɪndɪkeɪt/", "vt. 表明；指出；预示；象征"},
    {"indication", "/ˌɪndɪˈkeɪʃn/", "n. 指示，指出；迹象；象征"},
    {"indifferent", "/ɪnˈdɪfrənt/", "adj. 冷淡的；不关心的；中等的；平庸的；一般的；相当差的；中立的；不分化的n. 冷漠的人"},
    {"indignant", "/ɪnˈdɪɡnənt/", "adj. 愤愤不平的；义愤的"},
    {"indirect", "/ˌɪndəˈrekt/", "adj. 间接的；迂回的；非直截了当的"},
    {"indispensable", "/ˌɪndɪˈspensəbl/", "adj. 不可缺少的；绝对必要的；责无旁贷的n. 不可缺少之物；必不可少的人"},
    {"individual", "/ˌɪndɪˈvɪdʒuəl/", "adj. 个人的；个别的；独特的n. 个人，个体"},
    {"indoors", "/ˌɪnˈdɔːrz/", "adv. 在室内，在户内"},
    {"industrial", "/ɪnˈdʌstriəl/", "adj. 工业的，产业的；从事工业的；供工业用的；来自勤劳的n. 工业股票；工业工人"},
    {"industrialize", "/ɪnˈdʌstriəlaɪz/", "vt. 使工业化vi. 实现工业化"},
    {"industry", "/ˈɪndəstri/", "n. 产业；工业；勤勉"},
    {"inefficient", "/ˌɪnɪˈfɪʃnt/", "adj. 无效率的，效率低的；无能的"},
    {"inevitable", "/ɪnˈevɪtəbl/", "adj. 必然的，不可避免的"},
    {"inexpensive", "/ˌɪnɪkˈspensɪv/", "adj. 便宜的"},
    {"infant", "/ˈɪnfənt/", "n. 婴儿；幼儿；未成年人adj. 婴儿的；幼稚的；初期的；未成年的n. (Infant)人名；(英)因方特"},
    {"infect", "/ɪnˈfekt/", "vt. 感染，传染"},
    {"infer", "/ɪnˈfɜːr/", "vt. 推断；推论vi. 推断；作出推论"},
    {"inferior", "/ɪnˈfɪriər/", "adj. 差的；自卑的；下级的，下等的n. 下级；次品"},
    {"infinite", "/ˈɪnfɪnət/", "adj. 无限的，无穷的；无数的；极大的n. 无限；[数] 无穷大；无限的东西（如空间，时间）"},
    {"influence", "/ˈɪnfluəns/", "n. 影响；势力；感化；有影响的人或事vt. 影响；改变"},
    {"influential", "/ˌɪnfluˈenʃl/", "adj. 有影响的；有势力的n. 有影响力的人物"},
    {"inform", "/ɪnˈfɔːrm/", "vt. 通知；告诉；报告vi. 告发；告密"},
    {"information", "/ˌɪnfərˈmeɪʃn/", "n. 信息，资料；知识；情报"},
    {"inhabit", "/ɪnˈhæbɪt/", "vt. 栖息；居住于；占据vi. （古）居住；栖息"},
    {"inhabitant", "/ɪnˈhæbɪtənt/", "n. 居民；居住者"},
    {"inherit", "/ɪnˈherɪt/", "vt. 继承；遗传而得vi. 成为继承人"},
    {"initial", "/ɪˈnɪʃl/", "adj. 最初的；字首的vt. 用姓名的首字母签名n. 词首大写字母；原始细胞"},
    {"injection", "/ɪnˈdʒekʃn/", "n. 注射；注射剂；充血；射入轨道"},
    {"injure", "/ˈɪndʒər/", "vt. 伤害，损害"},
    {"injury", "/ˈɪndʒəri/", "n. 伤害，损害；受伤处"},
    {"ink", "/ɪŋk/", "n. 墨水，油墨; （乌贼分泌的）墨液 vt. 给…上油墨（以供印刷、签订合同等）; 签名（在…上）; 涂油墨"},
    {"inn", "/ɪn/", "n. 客栈；旅馆vi. 住旅馆n. (Inn)人名；(柬)因"},
    {"inner", "/ˈɪnər/", "adj. 内部的；内心的；精神的n. 内部"},
    {"innocent", "/ˈɪnəsnt/", "adj. 无辜的；无罪的；无知的n. 天真的人；笨蛋n. (Innocent)人名；(英、西)因诺森特；(法)伊诺桑"},
    {"input", "/ˈɪnpʊt/", "n. 投入；输入电路vt. [自][电子] 输入；将…输入电脑"},
    {"inquire", "/ɪnˈkwaɪər/", "vt. 询问；查究；问明vi. 询问；查究；询价"},
    {"inquiry", "/ɪnˈkwaɪəri; ˈɪnkwəri/", "n. 探究；调查；质询；询盘，询价"},
    {"insect", "/ˈɪnsekt/", "n. 昆虫；卑鄙的人"},
    {"insert", "/ɪnˈsɜːrt/", "v. 插入；（在文章中）添加；嵌入；附着；把……射入轨道；登载n. （书报的）插页；插入物；（服装面料的）布饰；（电影等的）插入镜头"},
    {"inside", "/ˌɪnˈsaɪd/", "n.里面,内部,内脏,内情adj.内部的,秘密的,于室内工作的adv.在里面 prep.在...之内"},
    {"insist", "/ɪnˈsɪst/", "vt. 坚持，强调vi. 坚持，强调"},
    {"inspect", "/ɪnˈspekt/", "vt. 检查；视察；检阅vi. 进行检查；进行视察"},
    {"inspection", "/ɪnˈspekʃn/", "n. 视察，检查"},
    {"inspire", "/ɪnˈspaɪər/", "vt. 激发；鼓舞；启示；产生；使生灵感"},
    {"install", "/ɪnˈstɔːl/", "vt. 安装；任命；安顿"},
    {"installation", "/ˌɪnstəˈleɪʃn/", "n. 安装，装置；就职"},
    {"instance", "/ˈɪnstəns/", "n. 实例；情况；建议vt. 举...为例"},
    {"instant", "/ˈɪnstənt/", "adj. 立即的；紧急的；紧迫的n. 瞬间；立即；片刻"},
    {"instantly", "/ˈɪnstəntli/", "adv. 立即地；马上地；即刻地conj. 一…就…"},
    {"instead", "/ɪnˈsted/", "adv. 代替；反而；相反"},
    {"instinct", "/ˈɪnstɪŋkt/", "n. 本能，直觉；天性adj. 充满着的"},
    {"institute", "/ˈɪnstɪtuːt/", "n. （尤指科学、教育的）机构，研究所，学会；机构建筑；（与法律相关的）注释，概要v. 实行，建立；授予……职位；提出（诉讼）"},
    {"institution", "/ˌɪnstɪˈtuːʃn/", "n. 制度；建立；（社会或宗教等）公共机构；习俗"},
    {"instruct", "/ɪnˈstrʌkt/", "vt. 指导；通知；命令；教授"},
    {"instruction", "/ɪnˈstrʌkʃn/", "n. 指令，命令；指示；教导；用法说明"},
    {"instrument", "/ˈɪnstrəmənt/", "n. 仪器；工具；乐器；手段；器械vt. 给……装测量仪器"},
    {"insufficient", "/ˌɪnsəˈfɪʃnt/", "adj. 不足的；不能胜任的，缺乏能力的"},
    {"insult", "/ɪnˈsʌlt; ˈɪnsʌlt     /", "v. 侮辱；辱骂；损害n. 侮辱；凌辱；无礼"},
    {"insurance", "/ɪnˈʃʊrəns/", "n. 保险；保险费；保险契约；赔偿金"},
    {"insure", "/ɪnˈʃʊr/", "vt. 给……保险；北美确保，保证vi. 投保；北美确保"},
    {"intellectual", "/ˌɪntəˈlektʃuəl/", "adj. 智力的；聪明的；理智的n. 知识分子；凭理智做事者"},
    {"intelligence", "/ɪnˈtelɪdʒəns/", "n. 智力；情报工作；情报机关；理解力；才智，智慧；天分"},
    {"intelligent", "/ɪnˈtelɪdʒənt/", "adj. 智能的；聪明的；理解力强的"},
    {"intend", "/ɪnˈtend/", "vt. 打算；想要；意指vi. 有打算"},
    {"intense", "/ɪnˈtens/", "adj. 强烈的；紧张的；非常的；热情的"},
    {"intensity", "/ɪnˈtensəti/", "n. 强度；强烈；[电子] 亮度；紧张"},
    {"intensive", "/ɪnˈtensɪv/", "adj. 加强的；集中的；透彻的；加强语气的n. 加强器"},
    {"intention", "/ɪnˈtenʃn/", "n. 意图；目的；意向；愈合"},
    {"intentional", "/ɪnˈtenʃənl/", "adj. 故意的；蓄意的；策划的"},
    {"interaction", "/ˌɪntərˈækʃn/", "n. 相互作用，相互影响；交流；[数] 交互作用；互动"},
    {"interest", "/ˈɪntrəst/", "n. 兴趣，爱好；利息；利益；趣味；同行vt. 使……感兴趣；引起……的关心；使……参与"},
    {"interesting", "/ˈɪntrəstɪŋ/", "adj. 有趣的；引起兴趣的，令人关注的"},
    {"interfere", "/ˌɪntərˈfɪr/", "vi. 干涉；妨碍；打扰vt. 冲突；介入"},
    {"interference", "/ˌɪntərˈfɪrəns/", "n. 干扰，冲突；干涉"},
    {"interior", "/ɪnˈtɪriər/", "n. 内部，里面；内景；内陆，腹地；内政，内务；本质adj. 内部的，里面的；内位的；内陆的，腹地的；内务的，内政的；心灵的，精神的；本质的"},
    {"intermediate", "/ˌɪntərˈmiːdiət/", "adj. 中间的，过渡的；中级的，中等的n. 中级生；（化合物）中间体，中间物；中介，媒介v. 充当调解人，起媒介作用"},
    {"internal", "/ɪnˈtɜːrnl/", "adj. 内部的；体内的；（机构）内部的；国内的；本身的；内心的；（大学生）本校生的n. 内脏；内部特征"},
    {"international", "/ˌɪntərˈnæʃnəl/", "adj. 国际的；国际通用的n. 国际体育比赛（选手）；外国人n. (International) 共产国际（组织）"},
    {"interpret", "/ɪnˈtɜːrprət/", "vt. 说明；口译vi. 解释；翻译"},
    {"interpretation", "/ɪnˌtɜːrprəˈteɪʃn/", "n. 解释；翻译；演出"},
    {"interpreter", "/ɪnˈtɜːrprətər/", "n. 解释者；口译者；注释器"},
    {"interrupt", "/ˌɪntəˈrʌpt/", "vt. 中断；打断；插嘴；妨碍vi. 打断；打扰n. 中断"},
    {"interruption", "/ˌɪntəˈrʌpʃn/", "n. 中断；干扰；中断之事"},
    {"interval", "/ˈɪntərvl/", "n. 间隔；间距；幕间休息"},
    {"interview", "/ˈɪntərvjuː/", "n. 接见，采访；面试，面谈vt. 采访；接见；对…进行面谈；对某人进行面试"},
    {"intimate", "/ˈɪntɪmət/", "adj. 亲密的；私人的；精通的；有性关系的n. 知己；至交vt. 暗示；通知；宣布"},
    {"into", "/ˈɪntuː/", "prep. 到……里面；触及，碰撞；朝，向；转向；关于；转变成；造成（某种结果）；除；对……很有兴趣n. (Into) （美）因托（人名）"},
    {"introduce", "/ˌɪntrəˈduːs/", "vt. 介绍；引进；提出；采用"},
    {"introduction", "/ˌɪntrəˈdʌkʃn/", "n. 介绍；引进；采用；入门；传入"},
    {"invade", "/ɪnˈveɪd/", "vt. 侵略；侵袭；侵扰；涌入vi. 侵略；侵入；侵袭；侵犯"},
    {"invasion", "/ɪnˈveɪʒn/", "n. 入侵，侵略；侵袭；侵犯"},
    {"invent", "/ɪnˈvent/", "vt. 发明；创造；虚构"},
    {"invention", "/ɪnˈvenʃn/", "n. 发明；发明物；虚构；发明才能"},
    {"inventor", "/ɪnˈventər/", "n. 发明家；[专利] 发明人；创造者"},
    {"invest", "/ɪnˈvest/", "vt. 投资；覆盖；耗费；授予；包围vi. 投资，入股；花钱买"},
    {"investigate", "/ɪnˈvestɪɡeɪt/", "v. 调查；研究"},
    {"investigation", "/ɪnˌvestɪˈɡeɪʃn/", "n. 调查；调查研究"},
    {"investment", "/ɪnˈvestmənt/", "n. 投资；投入；封锁"},
    {"invisible", "/ɪnˈvɪzəbl/", "adj. 无形的，看不见的；无形的；不显眼的，暗藏的"},
    {"invitation", "/ˌɪnvɪˈteɪʃn/", "n. 邀请；引诱；请帖；邀请函"},
    {"invite", "/ɪnˈvaɪt/", "vt. 邀请，招待；招致n. 邀请"},
    {"involve", "/ɪnˈvɑːlv/", "vt. 包含；牵涉；使陷于；潜心于"},
    {"inward", "/ˈɪnwərd/", "adj. 向内的；内部的；精神的；本质上的；熟悉的adv. 向内；内心里n. 内部；内脏；密友n. (Inward)人名；(英)英沃德"},
    {"iron", "/ˈaɪərn/", "n. 熨斗；烙铁；坚强vt. 熨；用铁铸成adj. 铁的；残酷的；刚强的vi. 熨衣；烫平n. (Iron)人名；(英)艾恩"},
    {"irregular", "/ɪˈreɡjələr/", "adj. 不整齐的；不规则的；不正常的；非正规的；不按时的；便秘的（委婉语）n. 不规则物；不合规格的产品；非正规军人员"},
    {"island", "/ˈaɪlənd/", "n. 岛；岛屿；安全岛；岛状物adj. 岛的vt. 孤立；使成岛状n. (Island)人名；(英)艾兰"},
    {"isolate", "/ˈaɪsəleɪt/", "vt.使隔离,使孤立,使绝缘,离析n.隔离种群"},
    {"issue", "/ˈɪʃuː/", "n. 问题；流出；期号；发行物vt. 发行，发布；发给；放出，排出vi. 发行；流出；造成……结果；传下"},
    {"it", "/ɪt/", " pron.它;Italy,意大利;Information Technology,信息技术"},
    {"Italian", "/ɪˈtæliən/", "adj. 意大利的；意大利语的；意大利文化的n. 意大利人；意大利语"},
    {"Italy", "/ˈɪtəli/", "n. 意大利（欧洲南部国家）"},
    {"item", "/ˈaɪtəm/", "n. 条款，项目；一则；一件商品（或物品）adv. 又，同上v. 记下；逐条列出"},
    {"its", "/ɪts/", "pron. 它的n. (Its)人名；(俄)伊茨"},
    {"itself", "/ɪtˈself/", "pron. 它自己；它本身"},
    NULL
};