
#include "../../../include/words_lib/lib4_3/u_4.h"
const char *u_4[][3] = {
    {"ugly", "/ˈʌɡli/", "adj. 丑陋的；邪恶的；令人厌恶的"},
    {"ultimate", "/ˈʌltɪmət/", "adj. 最终的；极限的；根本的n. 终极；根本；基本原则"},
    {"ultimately", "/ˈʌltɪmətli/", "adv. 最后；根本；基本上"},
    {"umbrella", "/ʌmˈbrelə/", "n. 雨伞；保护伞；庇护；伞形结构"},
    {"unable", "/ʌnˈeɪbl/", "adj. 不会的，不能的；[劳经] 无能力的；不能胜任的"},
    {"unbearable", "/ʌnˈberəbl/", "adj. 难以忍受的；承受不住的"},
    {"uncertain", "/ʌnˈsɜːrtn/", "adj. 无把握的；多变的；不确定的；信心不足的；靠不住的"},
    {"uncle", "/ˈʌŋkl/", "n. 叔叔；伯父；伯伯；舅父；姨丈；姑父"},
    {"uncomfortable", "/ʌnˈkʌmftəbl/", "adj. 不舒服的；不安的"},
    {"unconscious", "/ʌnˈkɑːnʃəs/", "adj. 无意识的；失去知觉的；不省人事的；未发觉的"},
    {"uncover", "/ʌnˈkʌvər/", "vt. 发现；揭开；揭露vi. 发现；揭示；揭去盖子"},
    {"under", "/ˈʌndər/", " prep.在...之下,在...之内,在...领导下,低于,假借adv.在下"},
    {"undergo", "/ˌʌndərˈɡoʊ/", "vt. 经历，经受；忍受"},
    {"undergraduate", "/ˌʌndərˈɡrædʒuət/", "n. 大学本科生；大学肄业生adj. 大学本科生的；大学肄业生的"},
    {"underground", "/ˌʌndərˈɡraʊnd/", "adv. 在地下；秘密地adj. 位于地下的；地下的；先锋派的，急进探索的v. 铺（电缆）于地下n. 地铁；秘密政治组织"},
    {"underline", "/ˌʌndərˈlaɪn/", "vt. 强调；在…下面划线；预告n. 下划线；下期节目预告"},
    {"underneath", "/ˌʌndərˈniːθ/", "adv.在下面 prep.在...的下面"},
    {"understand", "/ˌʌndərˈstænd/", "vt. 理解；懂；获悉；推断；省略；明白vi. 理解；懂得；熟悉"},
    {"understanding", "/ˌʌndərˈstændɪŋ/", "n. 谅解，理解；理解力；协议adj. 了解的；聪明的；有理解力的v. 理解；明白（understand的ing形式）"},
    {"undertake", "/ˌʌndərˈteɪk/", "vt. 承担，保证；从事；同意；试图"},
    {"undertaking", "/ˌʌndərˈteɪkɪŋ/", "n. 事业；企业；保证；殡仪业v. 同意；担任；许诺（undertake的ing形式）"},
    {"undo", "/ʌnˈduː/", "vt. 取消；解开；破坏；扰乱vi. 撤消"},
    {"undoubtedly", "/ʌnˈdaʊtɪdli/", "adv. 确实地，毋庸置疑地"},
    {"uneasy", "/ʌnˈiːzi/", "adj. 不舒服的；心神不安的；不稳定的"},
    {"unexpected", "/ˌʌnɪkˈspektɪd/", "adj. 意外的，想不到的"},
    {"unfair", "/ˌʌnˈfer/", "adj. 不公平的，不公正的"},
    {"unfortunate", "/ʌnˈfɔːrtʃənət/", "adj. 不幸的；令人遗憾的；不成功的"},
    {"unfortunately", "/ʌnˈfɔːrtʃənətli/", "adv. 不幸地"},
    {"unhappy", "/ʌnˈhæpi/", "adj. 不快乐的；不幸福的；不适当的"},
    {"uniform", "/ˈjuːnɪfɔːrm/", "adj. 统一的；一致的；相同的；均衡的；始终如一的n. 制服vt. 使穿制服；使成一样"},
    {"union", "/ˈjuːniən/", "n. 联盟，协会；工会；联合"},
    {"unique", "/juˈniːk/", "adj. 独特的，稀罕的；[数] 唯一的，独一无二的n. 独一无二的人或物n. (Unique)人名；(英)尤妮克"},
    {"unit", "/ˈjuːnɪt/", "n. 单位，单元；装置；[军] 部队；部件"},
    {"unite", "/juˈnaɪt/", "vt. 使…混合；使…联合；使…团结vi. 团结；联合；混合"},
    {"unity", "/ˈjuːnəti/", "n. 团结；一致；联合；个体n. (Unity)人名；(英)尤妮蒂"},
    {"universal", "/ˌjuːnɪˈvɜːrsl/", "adj. 普遍的；通用的；宇宙的；全世界的；全体的n. 一般概念；普通性"},
    {"universe", "/ˈjuːnɪvɜːrs/", "n. 宇宙；世界；领域"},
    {"university", "/ˌjuːnɪˈvɜːrsəti/", "n. 大学；综合性大学；大学校舍"},
    {"unjust", "/ˌʌnˈdʒʌst/", "adj. 不公平的，不公正的；非正义的"},
    {"unkind", "/ˌʌnˈkaɪnd/", "adj. 不友善的，不亲切的；刻薄的；（天气）恶劣的"},
    {"unknown", "/ˌʌnˈnoʊn/", "adj. 未知的；陌生的，默默无闻的n. 未知数；未知的事物，默默无闻的人"},
    {"unless", "/ənˈles/", "conj. 除非；若非prep. 除……之外"},
    {"unlike", "/ˌʌnˈlaɪk/", "prep. 不像，和……不同；与……不同，与……相反；非……的特征，不是……的特点adj. 不同的，不相似的，不像的conj. 不同于"},
    {"unlikely", "/ʌnˈlaɪkli/", "adj. 不太可能的；没希望的adv. 未必"},
    {"unload", "/ˌʌnˈloʊd/", "vt. 卸；摆脱…之负担；倾销vi. 卸货；退子弹"},
    {"unlucky", "/ʌnˈlʌki/", "adj. 不幸的；倒霉的；不吉利的"},
    {"unnecessary", "/ʌnˈnesəseri/", "adj. 不必要的；多余的，无用的"},
    {"unpleasant", "/ʌnˈpleznt/", "adj. 讨厌的；使人不愉快的"},
    {"unsatisfactory", "/ˌʌnˌsætɪsˈfæktəri/", "adj. 不令人满意的；不满足的；不符合要求的"},
    {"unstable", "/ʌnˈsteɪbl/", "adj. 不稳定的；动荡的；易变的"},
    {"unsuitable", "/ʌnˈsuːtəbl/", "adj. 不适合的；不适宜的；不相称的"},
    {"until", "/ənˈtɪl/", "conj. 到……时，直到……为止prep. 到……时，直到……为止"},
    {"unusual", "/ʌnˈjuːʒuəl/", "adj. 不寻常的；与众不同的；不平常的"},
    {"unusually", "/ʌnˈjuːʒuəli/", "adv. 特别地，及其，非常；异常地，不同寻常地"},
    {"unwilling", "/ʌnˈwɪlɪŋ/", "adj. 不愿意的；不情愿的；勉强的"},
    {"up", "/ʌp/", "adv.向上,到(较高的地方,北方),起来,起床 prep.向上,在上,沿adj.向上的,上行的"},
    {"upon", "/əˈpɑːn/", "prep. 在……之上；即将来临adv. 在上面地；此后"},
    {"upper", "/ˈʌpər/", "adj. 上面的，上部的；较高的n. 鞋面；兴奋剂（常用复数 uppers）n. （Upper）（英）厄珀（人名）"},
    {"upright", "/ˈʌpraɪt/", "adj. 正直的，诚实的；垂直的，直立的；笔直的；合乎正道的n. 垂直；竖立"},
    {"upset", "/ʌpˈset/", "vt. 使心烦；颠覆；扰乱vi. 翻倒adj. 心烦的；混乱的；弄翻的n. 混乱；翻倒；颠覆"},
    {"upstairs", "/ˌʌpˈsterz/", "adv. 在（或向）楼上；在（或向）上一层；智力上adj. 楼上的n. 楼上"},
    {"upward", "/ˈʌpwərd/", "adj. 向上的；上升的adv. 向上地；增涨地"},
    {"upwards", "/ˈʌpwərdz/", "adv. 向上；在上部；向上游"},
    {"urge", "/ɜːrdʒ/", "vt. 力劝，催促；驱策，推进n. 强烈的欲望，迫切要求；推动力vi. 强烈要求"},
    {"urgent", "/ˈɜːrdʒənt/", "adj. 紧急的；急迫的"},
    {"us", "/əs,ʌs/", "pron. 我们"},
    {"usage", "/ˈjuːsɪdʒ/", "n. 使用；用法；惯例"},
    {"use", "/juːz/", "n. 使用；用途；发挥vt. 使用，运用；利用；耗费n. （Use）（德）乌泽（人名）"},
    {"used", "/juːst; juːzd/", "adj. 习惯的；二手的，使用过的v. 用（use 的过去式和过去分词）"},
    {"useful", "/ˈjuːsfl/", "adj. 有用的，有益的；有帮助的"},
    {"useless", "/ˈjuːsləs/", "adj. 无用的；无效的"},
    {"user", "/ˈjuːzər/", "n. 用户；使用者n. （User）（土）乌塞尔（人名）"},
    {"usual", "/ˈjuːʒuəl,ˈjuːʒəl/", "adj. 通常的，惯例的；平常的"},
    {"usually", "/ˈjuːʒəli/", "adv. 通常，经常"},
    {"utility", "/juːˈtɪləti/", "n. 实用；效用；公共设施；功用adj. 实用的；通用的；有多种用途的"},
    {"utilize", "/ˈjuːtəlaɪz/", "vt. 利用"},
    {"utmost", "/ˈʌtmoʊst/", "adj. 极度的；最远的n. 极限；最大可能"},
    {"utter", "/ˈʌtər/", "adj. 完全的；彻底的；无条件的v. 说出；发出，表达；发射；使用伪钞n. (Utter) （美、瑞、德、加、法、俄、匈）乌特（人名）"},
    NULL
};